<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>UnityCommunityDebug</AssemblyName>
    <RootNamespace>UnityDebugger.Adapter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="UnityDebugger.Adapter.Tests" />
    <InternalsVisibleTo Include="UnityDebugger.TestAdapter" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\vendor\vscode-mono-debug\VSCodeDebug.csproj" />
    <ProjectReference Include="..\..\vendor\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft.csproj" />
    <ProjectReference Include="..\..\vendor\debugger-libs\Mono.Debugging\Mono.Debugging.csproj" />
    <ProjectReference Include="..\..\vendor\debugger-libs\Mono.Debugging.Soft\Mono.Debugging.Soft.csproj" />
  </ItemGroup>
</Project>
